name: Blog Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      deployments: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: output node version
        id: output-node-version
        run: echo "node-version=$(cat ./.node-version)" >> $GITHUB_OUTPUT

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.output-node-version.outputs.node-version }}
          cache: 'npm'

      - name: Configure AWS Credentials
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2.7.17

      - name: dependencies install
        run: npm ci

      - name: build
        env:
          CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
          CMS_SERVICE_DOMAIN: ${{ secrets.CMS_SERVICE_DOMAIN }}
        run: |
          npm run build -w packages/blog

      - name: deploy assets
        run: |
          aws s3 sync packages/blog/dist/_astro s3://assets-blog-kanicrub/assets \
            --cache-control "max-age=31536000,immutable" \
            --endpoint-url https://dc938bd26c1f0ebc388b6cea34c1fb3f.r2.cloudflarestorage.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_KEY }}
          AWS_DEFAULT_REGION: auto

      - name: copy _header file
        run: |
          cp ./packages/blog/src/_headers ./packages/blog/dist/_headers

      - name: deploy
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          projectName: blog-kanicrub-net
          directory: ./packages/blog/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
